### ISSUE TITLE
v1.x error: "Uncaught Error: Class 'Twig_Loader_Filesystem' not found in"

### ISSUE THREAD

**Issue by olets** [ninsuo/twigfiddle#55]
1.x is erroring for me before it gets off the ground. The code

```twig
1
```

gives me

```
Uncaught Error: Class 'Twig_Loader_Filesystem' not found in twigfiddle:cli/src/Fuz/Process/TwigEngine/V2TwigEngine.php:114 Stack trace: #0 twigfiddle:cli/src/Fuz/Process/TwigEngine/V2TwigEngine.php(35): Fuz\Process\TwigEngine\V2TwigEngine->loadBefore270('/var/www/twigfi...', '/var/www/twigfi...', '/var/www/twigfi...') #1 twigfiddle:cli/src/Fuz/Process/Service/ExecuteManager.php(58): Fuz\Process\TwigEngine\V2TwigEngine->load('/var/www/twigfi...', '/var/www/twigfi...', '/var/www/twigfi...') #2 twigfiddle:cli/src/Fuz/Process/Command/RunCommand.php(107): Fuz\Process\Service\ExecuteManager->executeFiddle(Object(Fuz\Process\Agent\FiddleAgent)) #3 twigfiddle:cli/src/Fuz/Process/Command/RunCommand.php(141): Fuz\Process\Command\RunCommand->process() #4 twigfiddle:cli/vendor/symfony/console/Command/Command.php(266): Fuz\Process\Command\RunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfon
```

Same error for anything else.

Fiddle: https://twigfiddle.com/lop40u

**Comment by olets** [comment]
The error is in the file

```
twigfiddle:cli/src/Fuz/Process/TwigEngine/V2TwigEngine.php
```

![image](https://user-images.githubusercontent.com/3282350/68048924-fcae3200-fcb7-11e9-9848-41fe01c18bed.png)

**Comment by ninsuo** [comment]
Hello @olets and thank you for your report.
Indeed, this issue seems to pop from Twig 1.38.0
Will have a look.
Alain

**Comment by olets** [comment]
Awesome! What a fast turnaround for a non-trivial fix 🏆
