### ISSUE TITLE
Twig 3.8.0: Uncaught Error: Call to undefined function Twig\Loader\str_contains()

### ISSUE THREAD

**Issue by ninsuo** [ninsuo/twigfiddle#87]
It seems that the yesterday's Twig 3.8.0 release does not run fiddles because of php 8 requirement:

```
Uncaught Error: Call to undefined function Twig\Loader\str_contains() in twigfiddle:cli/twig/uncompressed/Twig-3.8.0/src/Loader/FilesystemLoader.php:253 Stack trace: #0 twigfiddle:cli/twig/uncompressed/Twig-3.8.0/src/Loader/FilesystemLoader.php(188): Twig\Loader\FilesystemLoader->validateName() #1 twigfiddle:cli/twig/uncompressed/Twig-3.8.0/src/Loader/FilesystemLoader.php(131): Twig\Loader\FilesystemLoader->findTemplate() #2 twigfiddle:cli/twig/uncompressed/Twig-3.8.0/src/Environment.php(264): Twig\Loader\FilesystemLoader->getCacheKey() #3 twigfiddle:cli/src/Fuz/Process/TwigEngine/AbstractTwigEngine.php(45): Twig\Environment->getTemplateClass() #4 twigfiddle:cli/src/Fuz/Process/Service/ExecuteManager.php(66): Fuz\Process\TwigEngine\AbstractTwigEngine->render() #5 twigfiddle:cli/src/Fuz/Process/Command/RunCommand.php(107): Fuz\Process\Service\ExecuteManager->executeFiddle() #6 /var/www/twigfid
```

twigfiddle runs normally in any other Twig version.

This Twig version is using `symfony/polyfill-php80`, it needs to be added to the project.

**Comment by ninsuo** [comment]
fixed in 37f9a5195bf34e15dc03f680d5ced9948f2ee3e5
